### ISSUE TITLE
There was an error in xcode9 B6

### ISSUE THREAD

**Issue by SF-Simon** [ngquerol/Diurna#1]
/Users/a/Downloads/Diurna-master/Diurna/Main.storyboard:1: NSSplitViewController's 'view' outlet should not point to its NSSplitView, use the 'splitView' outlet instead.

**Comment by ngquerol** [comment]
As you probably could tell, this project was not very actively developed :) 
I've just begun to work on it again, and fixed this particular problem, among others.

Thanks for the pointer !
